### PR TITLE
Readme fixes

### PR DESCRIPTION
**Pull request by lechup**
* fixing Bill Of Materials
* adding goo.gl links to aliexpress.com

Based on @justi links

---
This change is [Reviewable](https://reviewable.io/reviews/enviromonitor/enviromonitorstation/8)

### CODE REVIEW

**Comment by zen** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 28 at r1](https://reviewable.io:443/reviews/enviromonitor/enviromonitorstation/8#-Kc3Wpn4euvFRnaTS_dh:-Kc3Wpn5nrmDLjS6rZgO:bwy01d2) ([raw file](https://github.com/enviromonitor/enviromonitorstation/blob/66f60ed0d230d28b516daf5aee3bd4a8572fd6dd/README.md#L28)):*
> ```Markdown
> - 12V or 5V heat plate (example: https://goo.gl/Pexr5R)
> - DC-DC step down power supply module, preferably based on LM2596 (example: https://goo.gl/TbNs1Y)
> - AC power supply with 12V DC output (example: https://goo.gl/fVu5LT)
> ```

Please "1A" power

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/enviromonitor/enviromonitorstation/8)*

**Comment by zen** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 21 at r1](https://reviewable.io:443/reviews/enviromonitor/enviromonitorstation/8#-Kc3XBDrIvXgSWnSXcbS:-Kc3XBDrIvXgSWnSXcbT:b98rexr) ([raw file](https://github.com/enviromonitor/enviromonitorstation/blob/66f60ed0d230d28b516daf5aee3bd4a8572fd6dd/README.md#L21)):*
> ```Markdown
> 
> ## Bill of Materials
> - Wemos D1 mini ESP8266 based development board (example: https://goo.gl/nk0Xvn)
> ```

All links should lead to EN version of aliexpress

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/enviromonitor/enviromonitorstation/8)*

**Comment by lechup** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[README.md, line 21 at r1](https://reviewable.io:443/reviews/enviromonitor/enviromonitorstation/8#-Kc3XBDrIvXgSWnSXcbS:-Kc3Y5YjkEAgn7FI8qcn:b-ce8jvj) ([raw file](https://github.com/enviromonitor/enviromonitorstation/blob/66f60ed0d230d28b516daf5aee3bd4a8572fd6dd/README.md#L21)):*
<details><summary><i>Previously, zen (Tomasz Napierala) wrote…</i></summary><blockquote>

All links should lead to EN version of aliexpress
</blockquote></details>

Hm... Try them on incognito mode. I think aliexpress is doing lot of redirects when it detects pl-PL language in Your browser...
All links should be in english.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/enviromonitor/enviromonitorstation/8)*

**Comment by lechup** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 28 at r1](https://reviewable.io:443/reviews/enviromonitor/enviromonitorstation/8#-Kc3Wpn4euvFRnaTS_dh:-Kc3ZL7G6c27hYygA0vk:b-896fix) ([raw file](https://github.com/enviromonitor/enviromonitorstation/blob/66f60ed0d230d28b516daf5aee3bd4a8572fd6dd/README.md#L28)):*
<details><summary><i>Previously, zen (Tomasz Napierala) wrote…</i></summary><blockquote>

Please "1A" power
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/enviromonitor/enviromonitorstation/8)*

**Comment by zen** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/enviromonitor/enviromonitorstation/8#-:-Kc4OwrCae_HRLKt6Lzg:bnfp4nl)*

**Comment by zen** [comment]
Sorry, I missed this one and generated conflict. Would you be able to rebase please?

**Comment by lechup** [comment]
Rebased

**Comment by zen** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[README.md, line 24 at r3](https://reviewable.io:443/reviews/enviromonitor/enviromonitorstation/8#-Kcdds5aJbHp0Ukduyor:-Kcdds5bu0E1ZW79YMID:b3zpv8k) ([raw file](https://github.com/enviromonitor/enviromonitorstation/blob/8f5ae598b3e698681c65312b541a54926b39db30/README.md#L24)):*
> Wemos D1 mini
I would note, that Mini Pro was not tested

---

*[README.md, line 26 at r3](https://reviewable.io:443/reviews/enviromonitor/enviromonitorstation/8#-KcdeQoIm-QRrnu5WpUs:-KcdeQoIm-QRrnu5WpUt:b-n1tv77) ([raw file](https://github.com/enviromonitor/enviromonitorstation/blob/8f5ae598b3e698681c65312b541a54926b39db30/README.md#L26)):*
> https://goo.gl/bCfaJp
This link only shows one offer, it should probably lead to search results

---

*[README.md, line 28 at r3](https://reviewable.io:443/reviews/enviromonitor/enviromonitorstation/8#-KcdebsKV3LHoTW7mlUk:-KcdebsKV3LHoTW7mlUl:by0xsp3) ([raw file](https://github.com/enviromonitor/enviromonitorstation/blob/8f5ae598b3e698681c65312b541a54926b39db30/README.md#L28)):*
> https://goo.gl/guQqyB
This leads to one shop only, is this ok?

---

*[README.md, line 29 at r3](https://reviewable.io:443/reviews/enviromonitor/enviromonitorstation/8#-Kcdg9eAc3CBK1zRW0KP:-Kcdg9eB7mzlcLVQuVkb:bxf18h2) ([raw file](https://github.com/enviromonitor/enviromonitorstation/blob/8f5ae598b3e698681c65312b541a54926b39db30/README.md#L29)):*
> https://goo.gl/Pexr5R
I would add variant here: 5V / 70 C / 2-4W

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/enviromonitor/enviromonitorstation/8)*

**Comment by zen** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/enviromonitor/enviromonitorstation/8#-:-KcdgTfcNRUK_PpaRTO1:bnfp4nl)*

**Comment by lechup** [comment]
@zen You need to add review on GH to actually be able to merge it through GH. Can You merge it?

**Review by zen — APPROVED** [review]

**Pull request merged**
